language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-pcastillol
  api_key:
    secure: NiLgEh57v5349rjdf7eXZptsCjmb8qlOhu4JFnX+/81xtsE3X5IWnAF3PkBeySWg66y3OMC/vQ1Ka+VBHXFxoGd9NOHkvMvvhB52HkrM1Co/rczpmO12SH8sh7GcudaVmc2XnNWtPFz8MRZij0TCRWlNppJiC1myPUQCDQsmYp5gGPGMvoQQ5wjJuiujlxBOASZj0G0dfovxziOZABvyh0RykflEYCKrb1WpwIsUejuUsUVwsF6r0my2O7Pae8pWETVs2MOqWFwIVCJ00vwMdLk/m75JpzpaXmQTAgZMPnuGqYcaDLvGFKaLXr0xlhE8aKfw585tYtuB4Ls37RsFV9pZLptEXelqBY3T11xgayXdx/SB+h7J0poTmaYLyc/5fSLMmfecdDWri/23ltgMr4Im25wd+P/Efqq5sqRv4CocCyEbltlCVwaYnMd9gOrxyYeM8tAoHEHkn2czYe3Sw2EAf2RKycJkSMdFp4B6ynjyKqY2760TCy8e4vt5l8zyum+A3FZnVSYFdioKYuUjCGxJrPKolS30vuQzwkMUWCewS7spJQc0i/PadqD9gk/ysUMbT4iHgemX3atpeisae2zQ6zTyhy8Fvk0JzgtnDSYLyGcSIfnjhv6GDk+34p+U3uea3v9QWo8BJM1C+q46Rc9FWQXFhx47Zo/7IRucvLA=
